/**
 * YouTube transcript import for notebook sources.
 *
 * No API key needed: public watch pages embed the player's caption-track
 * list, and each track serves WebVTT over plain HTTPS. Videos without any
 * captions (or private/region-blocked ones) fail with a friendly error.
 */

export interface YouTubeTranscript {
  videoId: string;
  title: string;
  author: string;
  languageCode: string;
  languageName: string;
  autoGenerated: boolean;
  text: string;
}

interface CaptionTrack {
  baseUrl: string;
  name?: { runs?: Array<{ text?: string }> };
  vssId?: string;
  languageCode?: string;
  kind?: string;
}

const WATCH_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

/** Accepts watch, youtu.be, embed, shorts, and live URLs (bare IDs too). */
export function extractYouTubeVideoId(input: string): string | null {
  const raw = input.trim();
  if (!raw) return null;
  if (/^[A-Za-z0-9_-]{11}$/.test(raw)) return raw;
  let url: URL;
  try {
    url = new URL(raw.includes("://") ? raw : `https://${raw}`);
  } catch {
    return null;
  }
  const host = url.hostname.replace(/^www\./, "").toLowerCase();
  if (host === "youtu.be") {
    const id = url.pathname.split("/").filter(Boolean)[0];
    return id && /^[A-Za-z0-9_-]{11}$/.test(id) ? id : null;
  }
  if (host.endsWith("youtube.com") || host.endsWith("youtube-nocookie.com")) {
    const v = url.searchParams.get("v");
    if (v && /^[A-Za-z0-9_-]{11}$/.test(v)) return v;
    const parts = url.pathname.split("/").filter(Boolean);
    const i = parts.findIndex((p) => p === "embed" || p === "shorts" || p === "live" || p === "v");
    if (i >= 0 && parts[i + 1] && /^[A-Za-z0-9_-]{11}$/.test(parts[i + 1])) return parts[i + 1];
  }
  return null;
}

/** Extracts a [...] JSON array starting at `from`, respecting strings. */
function extractJsonArray(html: string, from: number): string | null {
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = from; i < html.length; i++) {
    const ch = html[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) return html.slice(from, i + 1);
    }
  }
  return null;
}

function decodeJsonString(escaped: string): string {
  try {
    return JSON.parse(`"${escaped}"`);
  } catch {
    return escaped;
  }
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_m, n) => {
      try {
        return String.fromCharCode(Number(n));
      } catch {
        return "";
      }
    });
}

function vttTimestampToSeconds(ts: string): number {
  const parts = ts.trim().split(":").map((p) => Number(p));
  if (parts.some((n) => Number.isNaN(n))) return 0;
  let seconds = 0;
  for (const p of parts) seconds = seconds * 60 + p;
  return seconds;
}

function formatTimestamp(totalSeconds: number): string {
  const s = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  const mm = h > 0 ? String(m).padStart(2, "0") : String(m);
  return `${h > 0 ? `${h}:` : ""}${mm}:${String(sec).padStart(2, "0")}`;
}

interface Cue {
  start: number;
  text: string;
}

/** YouTube srv3 XML → cleaned cues (`<p t="ms">text</p>`). */
function parseSrv3(xml: string): Cue[] {
  const cues: Cue[] = [];
  const re = /<p\b[^>]*\bt="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml))) {
    const start = Number(m[1]) / 1000;
    const text = decodeHtmlEntities(m[2].replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim());
    if (!text) continue;
    const prev = cues[cues.length - 1];
    if (prev && (prev.text === text || (text.length > 12 && prev.text.includes(text)))) continue;
    cues.push({ start, text });
  }
  return cues;
}

function parseCaptionBody(body: string): Cue[] {
  const trimmed = body.trimStart();
  if (trimmed.startsWith("<?xml") || trimmed.startsWith("<timedtext")) return parseSrv3(body);
  return parseVtt(body);
}

/** WebVTT → cleaned cues (tags stripped, consecutive duplicates dropped). */
function parseVtt(vtt: string): Cue[] {
  const cues: Cue[] = [];
  const blocks = vtt.replace(/\r/g, "").split(/\n\s*\n/);
  for (const block of blocks) {
    const lines = block.split("\n").map((l) => l.trim()).filter(Boolean);
    if (!lines.length) continue;
    if (/^WEBVTT/i.test(lines[0])) lines.shift();
    const arrow = lines.findIndex((l) => l.includes("-->"));
    if (arrow < 0) continue;
    const start = vttTimestampToSeconds(lines[arrow].split("-->")[0]);
    const text = lines
      .slice(arrow + 1)
      .join(" ")
      .replace(/<[^>]*>/g, "")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;
    const decoded = decodeHtmlEntities(text);
    const prev = cues[cues.length - 1];
    // Auto captions repeat the previous line inside the next cue — skip
    // exact repeats and lines already fully contained in the previous cue.
    if (prev && (prev.text === decoded || (decoded.length > 12 && prev.text.includes(decoded)))) continue;
    cues.push({ start, text: decoded });
  }
  return cues;
}

/** Cues → readable paragraphs with [mm:ss] markers for grounding. */
function cuesToTranscript(cues: Cue[]): string {
  const paragraphs: string[] = [];
  let current: string[] = [];
  let currentStart = 0;
  let currentLen = 0;
  for (const cue of cues) {
    if (!current.length) currentStart = cue.start;
    current.push(cue.text);
    currentLen += cue.text.length + 1;
    if (currentLen >= 400) {
      paragraphs.push(`[${formatTimestamp(currentStart)}] ${current.join(" ")}`);
      current = [];
      currentLen = 0;
    }
  }
  if (current.length) paragraphs.push(`[${formatTimestamp(currentStart)}] ${current.join(" ")}`);
  return paragraphs.join("\n\n");
}

function pickTrack(tracks: CaptionTrack[], preferred = "en"): CaptionTrack | null {
  if (!tracks.length) return null;
  const lang = preferred.toLowerCase().split("-")[0];
  const scored = tracks.map((t) => {
    const code = (t.languageCode || "").toLowerCase();
    const manual = !t.kind || t.kind !== "asr";
    let score = 0;
    if (code === preferred.toLowerCase() || code === lang) score += 10;
    else if (code.startsWith("en")) score += 5;
    if (manual) score += 4;
    return { t, score };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored[0].t;
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, {
    headers: {
      "User-Agent": WATCH_UA,
      "Accept-Language": "en-US,en;q=0.9",
      Accept: "text/html,application/xhtml+xml",
    },
  });
  if (!res.ok) throw new Error(`YouTube request failed (HTTP ${res.status}).`);
  return res.text();
}

const INNERTUBE_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";

interface InnertubePlayer {
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: { title?: string; author?: string };
  captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] } };
}

/**
 * Primary path: the InnerTube player endpoint (ANDROID client) returns fresh
 * caption-track URLs that download fine where the embedded watch-page URLs
 * are throttled to empty responses. Returns null on any failure so the
 * watch-page scrape below can try instead.
 */
async function tryInnertubeTranscript(videoId: string, language: string): Promise<YouTubeTranscript | null> {
  try {
    const res = await fetch(`https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_KEY}`, {
      method: "POST",
      headers: { "User-Agent": WATCH_UA, "Content-Type": "application/json" },
      body: JSON.stringify({
        videoId,
        context: { client: { clientName: "ANDROID", clientVersion: "20.10.38", hl: "en", gl: "US" } },
      }),
    });
    if (!res.ok) return null;
    const player = (await res.json()) as InnertubePlayer;
    if (player.playabilityStatus?.status !== "OK") return null;
    const tracks = (player.captions?.playerCaptionsTracklistRenderer?.captionTracks || []).filter((t) => t.baseUrl);
    const track = pickTrack(tracks, language);
    if (!track?.baseUrl) return null;
    const capRes = await fetch(track.baseUrl + "&fmt=vtt", {
      headers: { "User-Agent": WATCH_UA, "Accept-Language": "en-US,en;q=0.9" },
    });
    if (!capRes.ok) return null;
    const cues = parseCaptionBody(await capRes.text());
    if (!cues.length) return null;
    const languageName = track.name?.runs?.map((r) => r.text || "").join("") || track.languageCode || language;
    return {
      videoId,
      title: player.videoDetails?.title || "YouTube video",
      author: player.videoDetails?.author || "",
      languageCode: track.languageCode || language,
      languageName,
      autoGenerated: track.kind === "asr",
      text: cuesToTranscript(cues),
    };
  } catch {
    return null;
  }
}

export async function fetchYouTubeTranscript(rawUrl: string, language = "en"): Promise<YouTubeTranscript> {
  const videoId = extractYouTubeVideoId(rawUrl);
  if (!videoId) throw new Error("That doesn't look like a YouTube link. Paste a watch, youtu.be, embed, or Shorts URL.");
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;

  const viaApi = await tryInnertubeTranscript(videoId, language);
  if (viaApi) return viaApi;

  let html: string;
  try {
    html = await fetchText(watchUrl);
  } catch (error) {
    throw new Error(`Could not reach YouTube: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (/id="consent-bump"/.test(html) || /consent\.youtube\.com/.test(html)) {
    throw new Error("YouTube asked for consent instead of the video — the video may be region-blocked or require sign-in.");
  }

  const tracksKey = '"captionTracks":';
  const tracksAt = html.indexOf(tracksKey);
  if (tracksAt < 0) {
    throw new Error("This video has no captions/subtitles available, so there is no transcript to import. (Private videos and some music clips have none.)");
  }
  const arrayStart = html.indexOf("[", tracksAt + tracksKey.length);
  const arrayJson = arrayStart >= 0 ? extractJsonArray(html, arrayStart) : null;
  if (!arrayJson) throw new Error("Could not read the video's caption list — YouTube may have changed its page format.");
  let tracks: CaptionTrack[];
  try {
    tracks = JSON.parse(arrayJson) as CaptionTrack[];
  } catch {
    throw new Error("Could not read the video's caption list — YouTube may have changed its page format.");
  }
  const track = pickTrack(tracks.filter((t) => t.baseUrl), language);
  if (!track?.baseUrl) throw new Error("This video has no usable caption tracks.");

  let title = "YouTube video";
  let author = "";
  const detailsMatch = html.match(/"videoDetails":\{"videoId":"[A-Za-z0-9_-]{11}","title":"((?:[^"\\]|\\.)*)"/);
  if (detailsMatch) title = decodeJsonString(detailsMatch[1]);
  const authorMatch = html.match(/"videoDetails":\{"videoId":"[A-Za-z0-9_-]{11}","title":"(?:[^"\\]|\\.)*","lengthSeconds":"\d+","keywords":\[[^\]]*\],"channelId":"[^"]*","isOwnerViewing":[^,]*,"shortDescription":[^,]*,"isCrawlable":[^,]*,"thumbnail":\{[^}]*\},"allowRatings":[^,]*,"viewCount":"[^"]*","author":"((?:[^"\\]|\\.)*)"/);
  if (authorMatch) author = decodeJsonString(authorMatch[1]);

  const vttUrl = track.baseUrl + (track.baseUrl.includes("?") ? "&" : "?") + "fmt=vtt";
  let body: string;
  try {
    const res = await fetch(vttUrl, { headers: { "User-Agent": WATCH_UA, "Accept-Language": "en-US,en;q=0.9" } });
    if (!res.ok) throw new Error(`caption download failed (HTTP ${res.status})`);
    body = await res.text();
  } catch (error) {
    throw new Error(`Could not download the captions: ${error instanceof Error ? error.message : String(error)}`);
  }
  const cues = parseCaptionBody(body);
  if (!cues.length) throw new Error("The captions downloaded empty — try another video.");
  const languageName = track.name?.runs?.map((r) => r.text || "").join("") || track.languageCode || language;

  return {
    videoId,
    title: decodeHtmlEntities(title),
    author: decodeHtmlEntities(author),
    languageCode: track.languageCode || language,
    languageName,
    autoGenerated: track.kind === "asr",
    text: cuesToTranscript(cues),
  };
}

/** Safe filename stem for the transcript source. */
export function youTubeSourceFilename(title: string): string {
  const stem = title
    .replace(/[<>:"/\\|?*\u0000-\u001f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80) || "YouTube video";
  return `YouTube - ${stem}.txt`;
}

/** Transcript → markdown document ready for the normal ingestion pipeline. */
export function youTubeTranscriptDocument(t: YouTubeTranscript): string {
  const header = [
    `# ${t.title} (YouTube)`,
    ``,
    `Source: https://www.youtube.com/watch?v=${t.videoId}`,
    ...(t.author ? [`Channel: ${t.author}`] : []),
    `Language: ${t.languageName} (${t.languageCode})`,
    `Captions: ${t.autoGenerated ? "auto-generated" : "manual subtitles"}`,
    ``,
    `## Transcript`,
    ``,
  ];
  return header.join("\n") + t.text + "\n";
}
