export type PlanItem = { content: string; status: "pending" | "in_progress" | "completed" };
export type AgentUsage = { inputTokens: number; outputTokens: number; totalTokens: number; estimatedCost: number };
export type SubagentRole = "researcher" | "tester" | "coder";
export type SubagentStep = { toolName: string; summary?: string; timestamp: string };
export type SubagentItem = { id: string; role: SubagentRole; task: string; status: "running" | "completed" | "failed"; steps: SubagentStep[]; output?: string; usage?: AgentUsage };
export type ArtifactStatus = "draft" | "pending_approval" | "approved" | "completed" | "rejected";
export type ArtifactItem = { id: string; sessionId: string; name: string; filename: string; path: string; content: string; status: ArtifactStatus; userFacing: boolean; requestFeedback: boolean; createdAt: string; updatedAt: string };
export type AgentEvent = { type: "status" | "tool" | "token" | "assistant" | "plan" | "error" | "usage" | "subagent" | "artifact"; text: string; timestamp: string; items?: PlanItem[]; usage?: AgentUsage; subagent?: SubagentItem; artifact?: ArtifactItem };
export type ProviderDefinition = { id: string; label: string; packageName: string; envKey: string; defaultBaseUrl?: string; models: string[] };
export type ProviderConfig = { id: string; label: string; provider: string; apiKey: string; baseUrl?: string; models: string[] };
export type SessionRecord = { id: string; title: string; createdAt: string; updatedAt: string; memory: string; checkpointId?: string; usage?: AgentUsage; messages: Array<{ role: "user" | "assistant" | "event"; text: string; images?: string[]; kind?: AgentEvent["type"]; createdAt: string; plan?: PlanItem[]; usage?: AgentUsage; subagent?: SubagentItem; artifact?: ArtifactItem }>; model?: { providerId: string; model: string } };
export type ProjectRecord = { id: string; name: string; root: string; createdAt: string; updatedAt: string; memory: string; sessions: SessionRecord[]; sandbox?: { provider: "local"; mode: "workspace-permissions"; status: string; path: string; lastSyncAt?: string } };
export type AppView = "chat" | "files" | "diff" | "terminal" | "browser" | "memory";
export type ChatItem = { role: "user" | "assistant" | "event"; text: string; images?: string[]; kind?: AgentEvent["type"]; createdAt: string; plan?: PlanItem[]; usage?: AgentUsage; subagent?: SubagentItem; artifact?: ArtifactItem };
export type FileEntry = { path: string; kind: "file" | "folder" };
export type WorkspaceDiffFile = { path: string; directory: string; name: string; additions: number; deletions: number; status: string; patch: string };
export type DiffSide = { number?: number; text: string };
export type SplitDiffRow = { kind: "context" | "change" | "added" | "deleted" | "hunk"; old?: DiffSide; new?: DiffSide; text?: string };
export type SandboxConfig = { provider: "local"; enabled: boolean; requireApproval: boolean; allowNetwork: boolean; commandTimeoutSeconds: number };
export type SandboxStatus = { configured: boolean; status: string; sandbox: ProjectRecord["sandbox"] | null };
export type McpTransport = "stdio" | "http" | "sse";
export type McpServerConfig = { id: string; name: string; enabled: boolean; transport: McpTransport; command?: string; args?: string[]; env?: Record<string, string>; url?: string; headers?: Record<string, string> };
export type McpTestResult = { ok: boolean; tools: string[]; error?: string };
export type SkillInfo = { name: string; description: string; path: string; source: "global" | "project" };
export type ConfirmDialogState = {
  title: string;
  message: string;
  confirmLabel?: string;
  danger?: boolean;
  onConfirm: () => void;
};
export type TrajectoryStep = { step_index: number; timestamp: string; source: string; type: string; content: string; thinking?: string; tool_calls?: Array<{ name: string; args: any }>; usage?: AgentUsage };
